redis:
  host: 127.0.0.1
  port: 6379
queue:
  type: simple
  host: 127.0.0.1
  port: 8098
kafka:
  bootstrap_servers: zoo-0:9092,zoo-1:9092,zoo-2:9092
  topic: pbft
  hb_topic: pbft-hb
  consumer_group_id: cg
runtime:
  profile: BalancedProfile
  data_transfer: False
  max_pending_elections: 10
  projected_queue_threshold: 300.00
  ready_queue_threshold: 100.00
  max_time_load_zero: 30
  restart_job_selection: 300
  peer_heartbeat_timeout: 300
  results_dir: pbft
  message_service_type: kafka
  shutdown_mode: manual
  heartbeat_mode: redis
  total_agents: 5
logging:
  ## The directory in which actor should create log files.
  ## This directory will be automatically created if it does not exist.
  log-directory: pbft

  ## The filename to be used for actor's log file.
  log-file: agent

  ## The default log level for actor.
  log-level: DEBUG 

  ## actor rotates log files. You may specify how many archived log files to keep here.
  log-retain: 5

  ## actor rotates log files after they exceed a certain size.
  ## You may specify the file size that results in a log file being rotated here.
  log-size: 5000000

  logger: agent
