# Based on https://riak.com/posts/technical/running-riak-in-docker/index.html?p=12629.html
services:
  coordinator:
    image: basho/riak-kv
    ports:
      - "8087:8087"
      - "8098:8098"
    environment:
      - CLUSTER_NAME=riakkv
    labels:
      - "com.basho.riak.cluster.name=riak-kv"
    volumes:
      - schemas:/etc/riak/schemas
      - "./99-tune-cfg.sh:/etc/riak/prestart.d/99-tune-cfg.sh:ro"
    network_mode: bridge
  member:
    image: basho/riak-kv
    ports:
      - "9087:8087"
      - "9098:8098"
    labels:
      - "com.basho.riak.cluster.name=riak-kv"
    links:
      - coordinator
    network_mode: bridge
    depends_on:
      - coordinator
    environment:
      - CLUSTER_NAME=riakkv
      - COORDINATOR_NODE=coordinator
    volumes:
      - "./99-tune-cfg.sh:/etc/riak/prestart.d/99-tune-cfg.sh:ro"
volumes:
  schemas: {}