# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from swarm.comm.colmena_consensus import colmena_consensus_pb2 as colmena__consensus_dot_colmena__consensus__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SchedulingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerRole = channel.unary_unary(
                '/colmena_consensus.SchedulingService/TriggerRole',
                request_serializer=colmena__consensus_dot_colmena__consensus__pb2.TriggerRoleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SchedulingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TriggerRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerRole': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerRole,
                    request_deserializer=colmena__consensus_dot_colmena__consensus__pb2.TriggerRoleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'colmena_consensus.SchedulingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SchedulingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriggerRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colmena_consensus.SchedulingService/TriggerRole',
            colmena__consensus_dot_colmena__consensus__pb2.TriggerRoleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SelectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestRoles = channel.unary_unary(
                '/colmena_consensus.SelectionService/RequestRoles',
                request_serializer=colmena__consensus_dot_colmena__consensus__pb2.RoleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SelectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestRoles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SelectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRoles,
                    request_deserializer=colmena__consensus_dot_colmena__consensus__pb2.RoleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'colmena_consensus.SelectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SelectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colmena_consensus.SelectionService/RequestRoles',
            colmena__consensus_dot_colmena__consensus__pb2.RoleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
