# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: colmena_consensus/colmena_consensus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)colmena_consensus/colmena_consensus.proto\x12\x11\x63olmena_consensus\x1a\x1bgoogle/protobuf/empty.proto\"I\n\x0bRoleRequest\x12%\n\x04role\x18\x01 \x01(\x0b\x32\x17.colmena_consensus.Role\x12\x13\n\x0bstartOrStop\x18\x02 \x01(\x08\"L\n\x12TriggerRoleRequest\x12\x0e\n\x06roleId\x18\x01 \x01(\t\x12\x11\n\tserviceId\x18\x02 \x01(\t\x12\x13\n\x0bstartOrStop\x18\x03 \x01(\x08\"Y\n\x04Role\x12\x0e\n\x06roleId\x18\x01 \x01(\t\x12\x11\n\tserviceId\x18\x02 \x01(\t\x12.\n\tresources\x18\x03 \x03(\x0b\x32\x1b.colmena_consensus.Resource\"\'\n\x08Resource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x32\x61\n\x11SchedulingService\x12L\n\x0bTriggerRole\x12%.colmena_consensus.TriggerRoleRequest\x1a\x16.google.protobuf.Empty2Z\n\x10SelectionService\x12\x46\n\x0cRequestRoles\x12\x1e.colmena_consensus.RoleRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')



_ROLEREQUEST = DESCRIPTOR.message_types_by_name['RoleRequest']
_TRIGGERROLEREQUEST = DESCRIPTOR.message_types_by_name['TriggerRoleRequest']
_ROLE = DESCRIPTOR.message_types_by_name['Role']
_RESOURCE = DESCRIPTOR.message_types_by_name['Resource']
RoleRequest = _reflection.GeneratedProtocolMessageType('RoleRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROLEREQUEST,
  '__module__' : 'colmena_consensus.colmena_consensus_pb2'
  # @@protoc_insertion_point(class_scope:colmena_consensus.RoleRequest)
  })
_sym_db.RegisterMessage(RoleRequest)

TriggerRoleRequest = _reflection.GeneratedProtocolMessageType('TriggerRoleRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRIGGERROLEREQUEST,
  '__module__' : 'colmena_consensus.colmena_consensus_pb2'
  # @@protoc_insertion_point(class_scope:colmena_consensus.TriggerRoleRequest)
  })
_sym_db.RegisterMessage(TriggerRoleRequest)

Role = _reflection.GeneratedProtocolMessageType('Role', (_message.Message,), {
  'DESCRIPTOR' : _ROLE,
  '__module__' : 'colmena_consensus.colmena_consensus_pb2'
  # @@protoc_insertion_point(class_scope:colmena_consensus.Role)
  })
_sym_db.RegisterMessage(Role)

Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCE,
  '__module__' : 'colmena_consensus.colmena_consensus_pb2'
  # @@protoc_insertion_point(class_scope:colmena_consensus.Resource)
  })
_sym_db.RegisterMessage(Resource)

_SCHEDULINGSERVICE = DESCRIPTOR.services_by_name['SchedulingService']
_SELECTIONSERVICE = DESCRIPTOR.services_by_name['SelectionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLEREQUEST._serialized_start=93
  _ROLEREQUEST._serialized_end=166
  _TRIGGERROLEREQUEST._serialized_start=168
  _TRIGGERROLEREQUEST._serialized_end=244
  _ROLE._serialized_start=246
  _ROLE._serialized_end=335
  _RESOURCE._serialized_start=337
  _RESOURCE._serialized_end=376
  _SCHEDULINGSERVICE._serialized_start=378
  _SCHEDULINGSERVICE._serialized_end=475
  _SELECTIONSERVICE._serialized_start=477
  _SELECTIONSERVICE._serialized_end=567
# @@protoc_insertion_point(module_scope)
