# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from swarm.comm import consensus_pb2 as swarm_dot_comm_dot_consensus__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in swarm/comm/consensus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConsensusServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/swarm.ConsensusService/SendMessage',
                request_serializer=swarm_dot_comm_dot_consensus__pb2.ConsensusMessage.SerializeToString,
                response_deserializer=swarm_dot_comm_dot_consensus__pb2.Ack.FromString,
                _registered_method=True)


class ConsensusServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsensusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=swarm_dot_comm_dot_consensus__pb2.ConsensusMessage.FromString,
                    response_serializer=swarm_dot_comm_dot_consensus__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarm.ConsensusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarm.ConsensusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsensusService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarm.ConsensusService/SendMessage',
            swarm_dot_comm_dot_consensus__pb2.ConsensusMessage.SerializeToString,
            swarm_dot_comm_dot_consensus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataTransferServiceStub(object):
    """---------------------------------------------------------------------------
    Data staging. A SEPARATE service, served on a SEPARATE port from
    ConsensusService, so a multi-megabyte transfer never queues behind — or ahead
    of — the consensus messages whose latency the evaluation measures, and so the
    transport's message counters keep counting consensus alone. Same host as
    consensus, so transfers traverse the same measured data-plane paths.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fetch = channel.unary_stream(
                '/swarm.DataTransferService/Fetch',
                request_serializer=swarm_dot_comm_dot_consensus__pb2.FetchRequest.SerializeToString,
                response_deserializer=swarm_dot_comm_dot_consensus__pb2.DataChunk.FromString,
                _registered_method=True)
        self.Put = channel.stream_unary(
                '/swarm.DataTransferService/Put',
                request_serializer=swarm_dot_comm_dot_consensus__pb2.PutChunk.SerializeToString,
                response_deserializer=swarm_dot_comm_dot_consensus__pb2.PutAck.FromString,
                _registered_method=True)


class DataTransferServiceServicer(object):
    """---------------------------------------------------------------------------
    Data staging. A SEPARATE service, served on a SEPARATE port from
    ConsensusService, so a multi-megabyte transfer never queues behind — or ahead
    of — the consensus messages whose latency the evaluation measures, and so the
    transport's message counters keep counting consensus alone. Same host as
    consensus, so transfers traverse the same measured data-plane paths.
    ---------------------------------------------------------------------------
    """

    def Fetch(self, request, context):
        """Stream one produced file. The server answers only for names it has itself
        published in `run_id`; an unknown name is refused by name, never joined onto
        a directory, so there is no path-traversal surface.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request_iterator, context):
        """Upload one produced file to a staging site, so an output outlives the agent
        that made it. Accepted ONLY by a server configured with a store directory --
        an ordinary agent serves what it produced and takes no uploads. Name and
        run_id are repeated on every chunk rather than sent once in a header: a few
        bytes against a 1 MiB payload, and it removes an entire class of "what if the
        first chunk never arrived" handling from the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fetch': grpc.unary_stream_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=swarm_dot_comm_dot_consensus__pb2.FetchRequest.FromString,
                    response_serializer=swarm_dot_comm_dot_consensus__pb2.DataChunk.SerializeToString,
            ),
            'Put': grpc.stream_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=swarm_dot_comm_dot_consensus__pb2.PutChunk.FromString,
                    response_serializer=swarm_dot_comm_dot_consensus__pb2.PutAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarm.DataTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarm.DataTransferService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataTransferService(object):
    """---------------------------------------------------------------------------
    Data staging. A SEPARATE service, served on a SEPARATE port from
    ConsensusService, so a multi-megabyte transfer never queues behind — or ahead
    of — the consensus messages whose latency the evaluation measures, and so the
    transport's message counters keep counting consensus alone. Same host as
    consensus, so transfers traverse the same measured data-plane paths.
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/swarm.DataTransferService/Fetch',
            swarm_dot_comm_dot_consensus__pb2.FetchRequest.SerializeToString,
            swarm_dot_comm_dot_consensus__pb2.DataChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/swarm.DataTransferService/Put',
            swarm_dot_comm_dot_consensus__pb2.PutChunk.SerializeToString,
            swarm_dot_comm_dot_consensus__pb2.PutAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
